In [3]:
import numpy as np
print(np.__version__)

2.5.1


In [4]:
a = np.array([1,2,3])

print(a)

[1 2 3]


In [6]:
b = np.array([4,5,6])
c = a + b
print(c)


[5 7 9]


In [ ]:
print(a.shape) #배열의 차원
print(a.size) #총 원소 개수

(3,)
3


In [8]:
#리스트로부터 생성
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [9]:
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
arr = np.ones((4,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
arr = np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [17]:
arr = np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [19]:
arr = np.random.randn(2,3) #2x3 배열
print(arr)

[[-0.78227644 -0.14457305 -1.87858577]
 [ 0.08749845  0.9543134   0.41760656]]


In [20]:
arr = np.array([[1,2,3],
                [4,5,6]]) # 2 x 3
print(arr.shape)

(2, 3)


shape : 배열의 모양

dimension : 배열의 차원

In [21]:
print(arr.ndim)

2


In [22]:
print(arr.dtype)

int64


In [23]:
arr = np.array([10,20,30,40,50])
# 10 30 50
print(arr[0],arr[2],arr[4])

10 30 50


In [25]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9,]])
print(arr[0,1])
print(arr[2,2]) 

2
9


In [29]:
arr = np.array(
    [
        [[1,2,3],[4,5,6]
         ],
         [
             [7,8,9],[10,11,12]
         ]
    ]
) #2x2x3
print(arr[1,0,2])
print(arr.shape)   #3차원

9
(2, 2, 3)


In [32]:
arr = np.array([10,20,30,40,50])
#([20,30,40])
#([10,20,30])
print(arr[1:4])
print(arr[:3])

[20 30 40]
[10 20 30]


In [34]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1: , :2])

[[4 5]
 [7 8]]


In [35]:
arr = np.array(
    [[
        [1,2,3],[4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]]
)
print(arr.shape)
print(arr[:, 1, ])

(2, 2, 3)
[[ 4  5  6]
 [10 11 12]]


In [ ]:
arr = np.array([10,20,30,40,50])
idx = [0,2,4]
print(arr[idx])
print(arr[[0:2:4]])

In [36]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
rows = [0,1,2]
cols = [2,1,0]
print(arr[rows,cols])

[3 5 7]


In [37]:
arr = np.array([10,20,30,40,50])
print(arr[arr>30])

[40 50]


In [40]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[arr>4])

[5 6 7 8 9]


In [41]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)

[5 7 9]


In [42]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 - arr2)

[-3 -3 -3]


In [43]:
print(arr1 * arr2)

[ 4 10 18]


In [44]:
print(arr1 / arr2)

[0.25 0.4  0.5 ]


In [45]:
print(arr1 ** 2)

[1 4 9]


In [47]:
print([1,2,3]*2)
(np.array([1,2,3])*2)

[1, 2, 3, 1, 2, 3]


array([2, 4, 6])

In [48]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.dot(arr1,arr2)) # 1*4 + 2*5 + 3*6

32


In [49]:
arr2d = np.array([[1,2],[3,4]])
arr1d = np.array([5,6])
print(arr2d.shape, arr1d.shape)
print(np.dot(arr2d,arr1d))

(2, 2) (2,)
[17 39]


In [51]:
arr2d = np.array([[1,2],[3,4]])
arr1d = np.array([[5,6],[7,8]])
print(arr2d.shape, arr1d.shape)
print(np.dot(arr2d,arr1d))

(2, 2) (2, 2)
[[19 22]
 [43 50]]


In [52]:
arr2d@arr1d

array([[19, 22],
       [43, 50]])

In [53]:
arr = np.array([1,2,3])
print(arr + 10)

[11 12 13]


In [54]:
arr = np.array([1,2,3])
arr1 = np.array([10,10,10])
print(arr + arr1)

[11 12 13]


In [55]:
arr2d = np.array([[1,2,3],[4,5,6]]) # 2 x 3
arr1d = np.array([1,2,3]) #3
print(arr2d + arr1d)

[[2 4 6]
 [5 7 9]]


In [56]:
arr3d = np.random.rand(3,1,4) #3x1x4배열
arr2d = np.random.rand(4,4)   #4x4 배열
result = arr3d + arr2d
print(result.shape)

(3, 4, 4)


In [58]:
arr2d = np.array([[1,2,3],[4,5,6]])

row = np.array([10,20,30])

col = np.array([[10],[20]])

print(arr2d.shape, row.shape, col.shape)

(2, 3) (3,) (2, 1)


In [59]:
print(arr2d + row)
print(arr2d + col)

[[11 22 33]
 [14 25 36]]
[[11 12 13]
 [24 25 26]]


In [61]:
arr = np.array([10,20,30])
print(arr > 15)
print(arr[arr > 15])

[False  True  True]
[20 30]


In [62]:
print(arr == 20) 
print(arr != 20)
print(arr[arr == 20])
print((arr[arr != 20]))

[False  True False]
[ True False  True]
[20]
[10 30]


In [64]:
arr1 = np.array([1,2,3])
arr2 = np.array([2,2,2])
print(arr1 > arr2)
print(arr1[arr1 > arr2])

[False False  True]
[3]


In [65]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.sum())  # 15

15


In [66]:
print(arr.max())  # 5
print(arr.min())  # 1

5
1


In [67]:
print(arr.mean())  # 3.0

3.0


In [68]:
print(arr.std())  # 표준편차
print(arr.var())  # 분산

1.4142135623730951
2.0


In [69]:
print(arr.cumsum())  # [1, 3, 6, 10, 15]

[ 1  3  6 10 15]


In [76]:
arr2d = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr2d.shape)
print(arr2d.sum(axis=0)) #각 열의 합 
print(arr2d.sum(axis=1)) #각 행의 합

(2, 3)
[5 7 9]
[ 6 15]


In [78]:
import numpy as np
arr = np.array([30,10,20,40,50])
sorted_arr = np.sort(arr)
print(sorted_arr)

[10 20 30 40 50]


In [79]:
sorted_arr_desc = np.sort(arr)[::-1]
sorted_arr_desc

array([50, 40, 30, 20, 10])

In [81]:
arr2d = np.array([
    [5,2,3],
    [8,4,1]
])
np.sort(arr2d)

array([[2, 3, 5],
       [1, 4, 8]])

In [82]:
arr = np.array([30,10,20])
sorted_indices = np.argsort(arr)
sorted_indices

array([1, 2, 0])

In [83]:
arr[sorted_indices]

array([10, 20, 30])

In [85]:
arr2d = np.array([
    [3,1,2],
    [6,4,5]
])

np.argsort(arr2d, axis=1)

array([[1, 2, 0],
       [1, 2, 0]])

In [86]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
merged_arr = np.concatenate((arr1, arr2))
print(merged_arr)

[1 2 3 4 5 6]


In [88]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
merged_arr = np.concatenate((arr1, arr2), axis = 0)
merged_arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [89]:
merged_arr = np.concatenate((arr1, arr2), axis=1)
print(merged_arr)
# [[1, 2, 5, 6],
#  [3, 4, 7, 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [90]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
merged_arr = np.vstack((arr1, arr2))
print(merged_arr)
# [[1, 2, 3],
#  [4, 5, 6]]

[[1 2 3]
 [4 5 6]]


In [91]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
merged_arr = np.hstack((arr1, arr2))
print(merged_arr)  # [1, 2, 3, 4, 5, 6]

[1 2 3 4 5 6]


In [92]:
#axis 0은 세로

In [94]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked_arr = np.stack((arr1, arr2), axis=0)
print(stacked_arr, stacked_arr.shape)
# [[1, 2, 3],
#  [4, 5, 6]]

[[1 2 3]
 [4 5 6]] (2, 3)


In [96]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

concat_arr = np.concatenate((arr1,arr2))
print("concat_arr : ", concat_arr, concat_arr.shape)
print('------------')
vs_arr = np.vstack((arr1, arr2))
print("vs_arr : ", vs_arr, vs_arr.shape)
print('-----------------')
hs_arr = np.hstack((arr1,arr2))
print("hs_arr: ", hs_arr, hs_arr.shape)
print('------------------')
stacked_arr = np.stack((arr1, arr2), axis = 0)
print("stacked_arr :", stacked_arr, stacked_arr, stacked_arr.shape)
print('-------------------')
stacked_arr_2 = np.stack((arr1, arr2), axis = 1)
print("stacked_arr_2 : ", stacked_arr_2, stacked_arr_2.shape)

concat_arr :  [1 2 3 4 5 6] (6,)
------------
vs_arr :  [[1 2 3]
 [4 5 6]] (2, 3)
-----------------
hs_arr:  [1 2 3 4 5 6] (6,)
------------------
stacked_arr : [[1 2 3]
 [4 5 6]] [[1 2 3]
 [4 5 6]] (2, 3)
-------------------
stacked_arr_2 :  [[1 4]
 [2 5]
 [3 6]] (3, 2)


In [97]:
import time
size = 1_000_000
python_list = list(range(size))

start_time = time.time()
python_list = [x * 2 for x in python_list]
print("Python 리스트 성능:", time.time() - start_time)

Python 리스트 성능: 0.03633522987365723


In [98]:
import numpy as np
np_array = np.arange(size)

start_time = time.time()
np_array = np_array * 2
print("NumPy 배열 성능:", time.time() - start_time)

NumPy 배열 성능: 0.0030565261840820312


In [99]:
size = 1000000
python_list = list(range(size))
result = []

start_time = time.time()
for x in python_list:
    result.append(x * 2)
print("반복문 성능:", time.time() - start_time)

반복문 성능: 0.08253049850463867


In [100]:
np_array = np.arange(size)

start_time = time.time()
np_array = np_array * 2  # 벡터화 연산
print("벡터화 성능:", time.time() - start_time)

벡터화 성능: 0.0020258426666259766


In [101]:
arr = np.array([1, 2, 3], dtype='int64')
print(arr.nbytes)  # 배열이 사용하는 메모리 크기 (bytes)

24


In [102]:
arr = np.array([1, 2, 3], dtype='int32')
print(arr.nbytes)  # 더 작은 메모리 사용

12


In [103]:
size = 100000000  # 1억 개의 요소
arr = np.random.rand(size)  # 난수 배열 생성

start_time = time.time()
result = np.sum(arr)  # 배열의 합 계산
print("대용량 데이터 합계 성능:", time.time() - start_time)

대용량 데이터 합계 성능: 0.0695796012878418


In [104]:
# 1GB 크기의 파일을 생성 후 메모리 맵핑 방식으로 읽기
size = 10**9
arr = np.memmap('large_file.dat', dtype='float32', mode='w+', shape=(size,))
arr[:100] = np.random.rand(100)  # 일부 데이터를 파일에 쓰기

# 파일을 메모리 맵핑하여 읽기
memmap_arr = np.memmap('large_file.dat', dtype='float32', mode='r', shape=(size,))
print(memmap_arr[:10])  # 메모리에 로드된 일부 데이터만 접근

[0.05235077 0.624198   0.19739492 0.5398176  0.55287325 0.13360654
 0.83256936 0.433268   0.07559461 0.89861465]
