NumPy를 사용하여 다음과 같은 배열을 생성해 보세요.

1. 크기가 4x3인 모든 값이 0인 배열
2. 크기가 3x3인 모든 값이 1인 배열
3. 0에서 20까지 5씩 증가하는 값으로 구성된 배열
4. 0과 1 사이의 4개의 등간격 값을 가진 배열
5. *크기가 2x2인 정규 분포로 구성된 배열*

In [1]:
import numpy as np

1. 크기가 4x3인 모든 값이 0인 배열

In [2]:
arr1 = np.zeros((4, 3))
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
arr2 = np.ones((3,3))
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [4]:
#3. 0에서 20까지 5씩 증가하는 값으로 구성된 배열

In [5]:
arr3 = np.arange(0,21,5)
print(arr3)

[ 0  5 10 15 20]


In [6]:
# 4. 0과 1 사이의 4개의 등간격 값을 가진 배열

In [7]:
arr4 = np.linspace(0,1,4)
print(arr4)

[0.         0.33333333 0.66666667 1.        ]


In [8]:
#5. 크기가 2x2인 정규 분포로 구성된 배열

In [9]:
arr5 = np.random.randn(2,2)
print(arr5)

[[ 5.39254549e-04 -7.81517857e-01]
 [-1.60131409e+00  9.02892457e-01]]


arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
1.배열 arr에서 1번째 열만 추출
2.배열 arr에서 2번째 행, 3번째 열의 값을 출력
3,배열 arr에서 0번째 행부터 1번째 행까지 선택하고, 0번째와 1번째 열만 추출

In [10]:
arr = np.array(
    [[10,20,30],
     [40,50,60],
     [70,80,90]])

In [11]:
np.shape(arr)

(3, 3)

In [12]:
#1. 배열 arr에서 1번째 열만 추출

In [13]:
print(arr[:,1])

[20 50 80]


In [14]:
# 2. 배열 arr에서 2번째 행, 2번째 열의 값을 출력
print(arr[2,2])

90


In [15]:

print(arr[0:2,0:2])

[[10 20]
 [40 50]]


아래 배열에서 팬시 인덱싱과 불리언 인덱싱을 사용하여 다음 작업을 수행하세요.
1. 팬시 인덱싱을 사용하여 배열의 0번째, 2번째, 4번째 요소를 출력
idx = [0,2,4]
print(arr[idx])
print(arr[[0,2,4]])

In [16]:
# 배열에서 팬시 인덱싱과 불리언 인덱싱을 사용하여 다음 작업을 수행하세요.
#1. 팬시 인덱싱을 사용하여 배열의 0번째, 2번째, 4번째 요소를 출력
arr = np.array([10,20,30,40,50])
idx = [0,2,4]
print(arr[idx])

[10 30 50]


In [17]:
arr = np.array([10,20,30,40,50])
arr[(arr > 15) & (arr < 45)]

array([20, 30, 40])

In [18]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[(arr % 2 ) == 0]

array([2, 4, 6, 8])

In [19]:
sales = np.array([[120, 150, 100],
                  [80, 90, 110],
                  [200, 180, 220],
                  [50, 45, 70],
                  [300, 320, 310]])

In [20]:
#월별 판매량이 200개 이상인 제품의 판매량을 선택하라.

In [21]:
arr = sales[(sales>=200)]
print(arr)

[200 220 300 320 310]


In [22]:
#3월(세 번째 열)의 판매량이 100개 이하인 제품의 1월과 2월 판매량을 추출하라.

In [23]:
arr2 = sales[0:2,0:1]
print(sales[sales[:,2]<=100, 0:2])

[[120 150]
 [ 50  45]]


In [24]:
#2월(두 번째 열)의 판매량이 150개 이상인 제품들의 전체 월별 판매량을 출력하라.

In [25]:
print(sales[sales[:,1] >= 150])

[[120 150 100]
 [200 180 220]
 [300 320 310]]


In [26]:
#다음 두 배열을 사용하여 각각의 요소별로 덧셈, 뺄셈, 곱셈, 나눗셈을 수행하세요.

In [27]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

In [28]:
print((arr1 + arr2))
print((arr1 - arr2))
print((arr1 * arr2))
print((arr1 / arr2))

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


In [29]:
#다음 두 배열 간의 내적 연산을 수행하세요.

In [30]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [31]:
print(arr1@arr2)

32


In [32]:
#아래의 2차원 배열과 1차원 배열을 브로드캐스팅하여 더하세요.

In [33]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])

In [34]:
print(arr2d + arr1d)

[[11 22 33]
 [14 25 36]]


In [35]:
#1. 배열에서 20보다 큰 값을 찾아 출력하세요.
#2. 배열의 합계, 최대값, 최소값, 평균을 계산하세요.

In [36]:
arr = np.array([10, 20, 30, 40, 50])

In [37]:
print(arr[(arr > 20)])

[30 40 50]


In [38]:
print(sum(arr))

150


In [39]:
print(max(arr))

50


In [40]:
print(min(arr))

10


In [41]:
print(arr.mean())

30.0


다음과 같은 과일 판매량 데이터가 있습니다. 각 과일의 1분기와 2분기 판매량이 주어졌을 때, NumPy 배열을 사용하여 아래 문제를 해결하세요.

1. 1분기와 2분기의 과일별 총 판매량을 구하세요.
2. 과일별 평균 판매량을 구하세요.

- **데이터**:
    - 1분기 판매량: `[200, 340, 150, 400]` (사과, 배, 오렌지, 바나나)
    - 2분기 판매량: `[220, 300, 180, 420]` (사과, 배, 오렌지, 바나나)
    

sales1 = np.array([200,340,150,400])
sales2 = np.array([220,300,180,420])

print(sum(sales1), sum(sales2))

In [42]:
sales1 = np.array([200,340,150,400])
sales2 = np.array([220,300,180,420])

In [43]:
print(sum(sales1))

1090


In [44]:
print(sum(sales2))

1120


In [45]:
print(sum(sales1+sales2)/2)

1105.0


In [46]:
arr = np.array([10, 20, 30, 40,50,100])
print(np.mean(arr))  # 25.0

41.666666666666664


In [47]:
print(np.median(arr))

35.0


In [48]:
from scipy import stats

arr = np.array([10, 20, 20, 30, 40])
print(stats.mode(arr))  # Mode: 20

ModeResult(mode=np.int64(20), count=np.int64(2))


In [49]:
print(np.var(arr))  # 125.0

104.0


In [50]:
    print(np.std(arr))  # 11.1803

10.198039027185569


In [51]:
print(np.max(arr) - np.min(arr))  # 30

30


In [52]:
arr = np.random.randn(1000)  # 평균 0, 표준편차 1인 정규분포 난수 1000개
print(np.mean(arr), np.std(arr))

0.0006286173172296472 0.9932422433732419


In [53]:
arr = np.random.uniform(0, 1, 1000)  # 0과 1 사이의 균등분포 난수 1000개
print(np.mean(arr), np.std(arr))

0.505334408883925 0.28471157875596614


In [54]:
#아래 배열에서 평균, 중앙값, 최빈값, 분산, 표준편차, 범위를 계산하세요.


In [55]:
arr = np.array([10, 20, 30, 30, 40, 50, 60])

In [56]:
print(np.mean(arr))
print(np.median(arr))
print(np.var(arr))
print(np.std(arr))
print(np.max(arr) - np.min(arr))

34.285714285714285
30.0
253.06122448979593
15.90789817951435
50


In [57]:
from scipy import stats
print(stats.mode(arr))

ModeResult(mode=np.int64(30), count=np.int64(2))


In [58]:
#정규분포와 균등분포에서 각각 난수를 생성하여, 평균과 표준편차를 계산하세요.

#1. 평균 0, 표준편차 1인 정규분포 난수 1000개 생성
#2. 0과 1 사이의 균등분포 난수 1000개 생성

In [59]:
arr1 = np.random.randn(1000)
arr2 = np.random.uniform(0,1,1000)

In [60]:
print(np.mean(arr1))
print(np.mean(arr2))
print(np.std(arr1))
print(np.std(arr2))

-0.003476772187412573
0.5112380804697116
1.0030950649669055
0.2933166105317912


아래와 같이 학생별 과목 성적 데이터가 주어졌을 때, 각 학생의 전체 평균 성적(수학, 영어, 과학)을 계산한 후, 이 평균값에 대한 분산과 표준편차를 구하세요.

In [61]:
# 학생별 과목 성적 데이터
scores_math = [88, 92, 76, 85, 95, 92, 88, 90, 85, 88]
scores_english = [90, 85, 80, 87, 92, 89, 83, 91, 86, 88]
scores_science = [85, 88, 82, 89, 94, 86, 91, 88, 84, 87]

In [62]:
arr = np.array([scores_math,scores_english,scores_science])
print(np.mean(arr,axis = 0)) #axis = 0은 세로

[87.66666667 88.33333333 79.33333333 87.         93.66666667 89.
 87.33333333 89.66666667 85.         87.66666667]


In [63]:
print(np.var(arr,axis = 0))

[ 4.22222222  8.22222222  6.22222222  2.66666667  1.55555556  6.
 10.88888889  1.55555556  0.66666667  0.22222222]


In [64]:
print(np.std(arr, axis = 0))

[2.05480467 2.86744176 2.49443826 1.63299316 1.24721913 2.44948974
 3.29983165 1.24721913 0.81649658 0.47140452]


In [65]:
#다음 1차원 배열을 오름차순 및 내림차순으로 정렬하세요.

In [66]:
arr = np.array([50, 10, 30, 40, 20])

In [67]:
sorted_arr = np.sort(arr)
print(sorted_arr)  # [10, 20, 30, 40, 50]

[10 20 30 40 50]


In [68]:
sorted_arr_desc = np.sort(arr)[::-1]
print(sorted_arr_desc)  # [50, 40, 30, 20, 10]

[50 40 30 20 10]


In [69]:
#다음 2차원 배열을 행과 열을 기준으로 각각 정렬하세요.

In [ ]:
arr2d = np.array([[8, 3, 5],
                  [2, 9, 1]])

In [71]:
sorted_arr_axis1 = np.sort(arr2d, axis=1)  #행 기준
print(sorted_arr_axis1)
# [[2, 3, 5],
#  [1, 4, 8]]

[[3 5 8]
 [1 2 9]]


In [72]:
sorted_arr_axis0 = np.sort(arr2d, axis=0) # 열 기준
print(sorted_arr_axis0)
# [[5, 2, 1],
#  [8, 4, 3]]

[[2 3 1]
 [8 9 5]]


In [73]:
#### **실습 3] 인덱스를 반환하는 정렬**

#다음 1차원 배열에서 정렬된 결과의 인덱스를 반환하고, 그 인덱스를 사용하여 배열을 정렬하세요.



In [74]:
arr = np.array([15, 10, 20])

In [77]:
print(np.argsort(arr))
print(arr[np.argsort(arr)])
print(arr)

[1 0 2]
[10 15 20]
[15 10 20]


In [78]:
#다음 두 개의 1차원 배열을 np.concatenate()와 np.hstack()을 사용하여 병합하세요.

In [79]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [81]:
merged_arr = np.concatenate((arr1,arr2))
print(merged_arr)

[1 2 3 4 5 6]


In [82]:
merged_arr2 = np.hstack((arr1,arr2))

In [83]:
print(merged_arr2)

[1 2 3 4 5 6]


In [84]:
#다음 두 개의 2차원 배열을 np.concatenate()와 np.vstack()을 사용하여 각각 병합하세요.

In [85]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

In [89]:
merged_arrs = np.concatenate((arr1, arr2))
print(merged_arrs)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [90]:
merged_arrs2 = np.vstack((arr1,arr2))

In [91]:
print(merged_arrs2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [92]:
#다음 두 개의 1차원 배열을 np.stack()을 사용하여 새로운 축을 따라 병합하세요.

In [93]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [94]:
ar1 = np.stack((arr1,arr2), axis = 0)
print(ar1)

[[1 2 3]
 [4 5 6]]


In [95]:
ar2 = np.stack((arr1,arr2), axis = 1)
print(ar2)

[[1 4]
 [2 5]
 [3 6]]


다음은 5개 지점에서 판매된 과일에 대한 월별 판매량 데이터입니다. 이 데이터는 각 지점의 판매량을 월별로 나타내며, 각 지점에서 판매된 사과, 바나나, 오렌지의 판매량이 기록되어 있습니다. 이 데이터를 사용하여 여러 가지 통계적 분석과 배열 조작을 수행하세요.

1. 각 지점에서 6개월 동안 판매된 **사과**, **바나나**, **오렌지**의 월별 평균 판매량을 계산하세요.
2. 각 월마다 전체 지점에서 가장 많이 판매된 과일을 찾아 판매량과 과일명을 출력하세요.
3. 전체 지점에서 과일별 총 판매량을 구하고, 가장 많이 판매된 과일을 찾는다.
4. 각 지점에서 판매량이 150개 이상인 데이터를 추출하고 그에 해당하는 지점과 과일을 출력하세요.

In [96]:
import numpy as np

# 5개 지점의 월별 사과, 바나나, 오렌지 판매량 (5x3x6 배열)
# 5개의 지점, 3개의 과일(사과, 바나나, 오렌지), 6개월치 데이터
sales_data = np.array([
    # 지점 1
    [[120, 150, 200, 230, 180, 210],  # 사과 판매량
     [100, 140, 170, 190, 160, 180],  # 바나나 판매량
     [90, 120, 160, 140, 130, 150]],  # 오렌지 판매량

    # 지점 2
    [[80, 90, 110, 140, 130, 120],
     [60, 70, 90, 100, 110, 95],
     [50, 80, 100, 110, 90, 85]],

    # 지점 3
    [[130, 140, 160, 180, 170, 190],
     [110, 120, 130, 150, 140, 160],
     [100, 110, 120, 130, 120, 140]],

    # 지점 4
    [[100, 130, 150, 170, 160, 180],
     [90, 100, 110, 120, 130, 125],
     [80, 110, 140, 130, 120, 110]],

    # 지점 5
    [[90, 110, 130, 140, 120, 130],
     [70, 85, 100, 110, 105, 95],
     [60, 90, 110, 100, 90, 95]]
])

In [113]:
sales_data.shape # (지점,과일,개월)

(5, 3, 6)

In [116]:
#1. 각 지점에서 사과, 바나나, 오렌지의 평균 판매량
avg_sales = np.mean(sales_data, axis=2)

print("지점별 과일 평균 판매량")
print(avg_sales)
print("shape:", avg_sales.shape)

지점별 과일 평균 판매량
[[181.66666667 156.66666667 131.66666667]
 [111.66666667  87.5         85.83333333]
 [161.66666667 135.         120.        ]
 [148.33333333 112.5        115.        ]
 [120.          94.16666667  90.83333333]]
shape: (5, 3)


In [118]:
#2. 각 월마다 전체 지점에서 가장 많이 판매된 과일과 판매량 출력

#5개 지점의 판매량을 합산
# 결과 shape: (3,6) = 과일 3개 x 6개월
total_sales = np.sum(sales_data, axis = 0)
print("전체 지점 합산 과일별 월별 판매량")
print(total_Sales)

#각 월마다 가장 높은 판매량
max_sales = np.max(total_Sales, axis = 0)

#각 월마다 가장 많이 팔린 과일의 index
max_sales_indices = np.argmax(total_sales, axis = 0)

fruits = ["사과",'바나나','오렌지']

for i max_Sale in enumerate(max_sales):
    fruit_name = fruits[max_sales_indices[i]]
    print(f"{i+1}월에 가장 많이 판매된 과일 : {fruit_name}, 판매량 : {max_sale}")

SyntaxError: invalid syntax (4021058501.py, line 17)

In [123]:
# axis = (0,2)는 index 0 지점과 index 2월을 합산하여 과일 축만 남겨 합산
total_sales = np.sum(sales_data, axis=(0,2))
print("과일별 총 판매량 : ", total_sales)

max_sales_index = np.argmax(total_sales)
max_Sales_value = total_sales[max_sales_index]

fruits = ['사과','바나나','오렌지']

print(f"가장 많이 판매된 과일 index : {max_sales_index}")
print(f"가장 많이 판매된 과일 : {fruits[max_sales_index]}, 총 판매량 : {max_sales_value}")

과일별 총 판매량 :  [4340 3515 3260]
가장 많이 판매된 과일 index : 0


NameError: name 'max_sales_value' is not defined

In [125]:
high_sales = sales_data >= 150
high_sales_indices =np.where(high_sales)

fruits = ['사과','바나나','오렌지']

print("판매량 150개 이상인 데이터")
print(sales_data[high_sales])

for branch_idx, fruit_idx, month_idx, in zip(*high_sales_indices):
    branch = branch_idx + 1
    month = month_idx + 1
    fruit_name = fruits[fruit_idx]
    sales = sales_data[branch_idx, fruit_idx, month_idx]

    print((f"{month}월 지점 {branch}, 과일 : {fruit_name}, 판매량 : {sales}"))

판매량 150개 이상인 데이터
[150 200 230 180 210 170 190 160 180 160 150 160 180 170 190 150 160 150
 170 160 180]
2월 지점 1, 과일 : 사과, 판매량 : 150
3월 지점 1, 과일 : 사과, 판매량 : 200
4월 지점 1, 과일 : 사과, 판매량 : 230
5월 지점 1, 과일 : 사과, 판매량 : 180
6월 지점 1, 과일 : 사과, 판매량 : 210
3월 지점 1, 과일 : 바나나, 판매량 : 170
4월 지점 1, 과일 : 바나나, 판매량 : 190
5월 지점 1, 과일 : 바나나, 판매량 : 160
6월 지점 1, 과일 : 바나나, 판매량 : 180
3월 지점 1, 과일 : 오렌지, 판매량 : 160
6월 지점 1, 과일 : 오렌지, 판매량 : 150
3월 지점 3, 과일 : 사과, 판매량 : 160
4월 지점 3, 과일 : 사과, 판매량 : 180
5월 지점 3, 과일 : 사과, 판매량 : 170
6월 지점 3, 과일 : 사과, 판매량 : 190
4월 지점 3, 과일 : 바나나, 판매량 : 150
6월 지점 3, 과일 : 바나나, 판매량 : 160
3월 지점 4, 과일 : 사과, 판매량 : 150
4월 지점 4, 과일 : 사과, 판매량 : 170
5월 지점 4, 과일 : 사과, 판매량 : 160
6월 지점 4, 과일 : 사과, 판매량 : 180
