# fastText

https://github.com/facebookresearch/fastText

**FastText**는 자연어 처리(NLP) 작업에서 사용되는 오픈소스 라이브러리로, 텍스트 분류 및 단어 임베딩을 위한 빠르고 효율적인 도구이다. 이는 Facebook AI Research 팀에서 개발했으며, 특히 대규모 텍스트 데이터에서도 높은 성능과 속도를 제공한다.

FastText는 2016년에 Facebook AI Research(FAIR) 팀에 의해 처음 공개되었다.  
처음 발표된 논문은 **"Enriching Word Vectors with Subword Information"** (2016)이며, 이후 오픈소스로 GitHub에 공개되어 많은 사용자들에게 활용되고 있다.  

FastText는 Word2Vec 이후 등장한 모델로, 특히 서브워드 정보 활용과 텍스트 분류에서 효율성을 강조하면서 주목받았다.

**주요 특징**
1. **단어 벡터 학습 (Word Embeddings)**  
   - FastText는 단어를 고정된 크기의 벡터로 변환하는 단어 임베딩 모델을 학습한다. 이는 단어의 의미를 벡터 공간에 매핑하여 유사한 단어가 가까운 벡터로 표현되도록 한다.
   - 기존의 Word2Vec과 유사하지만, FastText는 단어를 **서브워드(subword)** 단위로 처리한다.

2. **서브워드 기반 모델 (Subword-based Model)**  
   - 단어를 n-그램(예: 'apple' → ['app', 'ppl', 'ple'])으로 분해하여 학습하기 때문에, **희귀 단어**나 **철자 오류**에도 강건하다.
   - 이는 단어 외에도 철자 패턴과 같은 더 세밀한 정보를 학습하는 데 유용하다.

3. **텍스트 분류 (Text Classification)**  
   - FastText는 문서나 문장을 빠르고 정확하게 분류하는 데 최적화되어 있다.
   - 학습 과정이 빠르고, 모델의 크기가 작으며, 정확도도 뛰어나다.

4. **효율적인 구현**  
   - FastText는 CPU 기반으로도 높은 성능을 내도록 설계되었으며, 대규모 데이터셋에서도 빠르게 작동한다.

**FastText의 작동 원리**
1. **단어 표현**  
   - 단어를 n-그램 서브워드로 나눈 후, 각 서브워드에 대해 벡터를 학습한다.
   - 예를 들어, "cat"이라는 단어는 'c', 'ca', 'cat'과 같은 다양한 조합으로 분해된다.
   - 결과적으로 단어 벡터는 각 서브워드 벡터의 합으로 표현된다.

2. **모델 구조**  
   - FastText는 Skip-gram 모델이나 CBOW 모델을 기반으로 동작한다.
   - 단, 기존 모델과 달리 단어 자체가 아닌 서브워드를 사용하여 학습한다.

**FastText의 장점**
1. **희귀 단어 처리 능력**  
   - 서브워드 기반 접근 방식 덕분에 희귀 단어 또는 새로운 단어에 대해 더 좋은 일반화 성능을 발휘한다.
2. **빠른 학습 속도**  
   - 단순한 모델 구조와 최적화된 구현으로 매우 빠르게 학습할 수 있다.
3. **다양한 언어 지원**  
   - 다양한 언어에서 동작하며, 특히 굴절어(inflected languages)와 같은 복잡한 언어에서도 효과적이다.

**활용 사례**
1. **단어 임베딩**  
   - 단어 간 유사도 계산, 문장 표현 학습.
2. **텍스트 분류**  
   - 스팸 필터링, 감정 분석, 뉴스 분류.
3. **다언어 지원**  
   - 다국어 데이터셋에서 빠른 응답 성능 제공.

In [29]:
!gdown https://drive.google.com/uc?id=1vyZuUgbejAnx8xicQnQ1HgtW6avN8ZRQ

Downloading...
From (original): https://drive.google.com/uc?id=1vyZuUgbejAnx8xicQnQ1HgtW6avN8ZRQ
From (redirected): https://drive.google.com/uc?id=1vyZuUgbejAnx8xicQnQ1HgtW6avN8ZRQ&confirm=t&uuid=5822b9ae-173f-4995-a978-42dc3a5c4225
To: c:\Users\SJ\OneDrive\Desktop\study\NLP\03_text_vectorization\ted_en-20160408.xml

  0%|          | 0.00/74.5M [00:00<?, ?B/s]
  1%|          | 524k/74.5M [00:00<00:17, 4.28MB/s]
  4%|▍         | 3.15M/74.5M [00:00<00:04, 15.1MB/s]
 11%|█▏        | 8.39M/74.5M [00:00<00:02, 26.1MB/s]
 23%|██▎       | 16.8M/74.5M [00:00<00:01, 44.9MB/s]
 32%|███▏      | 23.6M/74.5M [00:00<00:01, 50.7MB/s]
 40%|████      | 29.9M/74.5M [00:00<00:00, 53.6MB/s]
 49%|████▊     | 36.2M/74.5M [00:00<00:00, 54.8MB/s]
 58%|█████▊    | 43.0M/74.5M [00:00<00:00, 57.9MB/s]
 66%|██████▌   | 49.3M/74.5M [00:01<00:00, 53.6MB/s]
 75%|███████▌  | 56.1M/74.5M [00:01<00:00, 57.4MB/s]
 85%|████████▌ | 63.4M/74.5M [00:01<00:00, 60.5MB/s]
 94%|█████████▎| 69.7M/74.5M [00:01<00:00, 60.1MB/s]
10

In [30]:
import nltk

nltk.download('punkt')
nltk.download('punkt tab')
nltk.download('stop wordls')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\SJ\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Error loading punkt tab: Package 'punkt tab' not found in
[nltk_data]     index
[nltk_data] Error loading stop wordls: Package 'stop wordls' not found
[nltk_data]     in index


False

2016 TED 강연 자막 데이터셋

In [31]:
from lxml import etree  # XML 파싱/검색 도구

xml = open('ted_en-20160408.xml', 'r', encoding = 'UTF8')
tree = etree.parse(xml) # XML 파일을 파싱해서 트리 구조로 로드

content = tree.xpath('//content/text()') # Xpath로 모든 <content> 태그의 텍스트 추출
print(len(content))

corpus = '\n'.join(content) # 하나의 텍스트 코퍼스로 생성

2085


In [32]:
# 텍스트 정재 + 토큰화 + 불용어 제거
import re
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords

corpus = re.sub(r'\([^)]*\)', '', corpus) # 괄호 (...) 안 텍스트 제거 (예 : (Applause))
corpus = re.sub(r'[^a-z0-9\s.,!?]+', '', corpus, flags = re.IGNORECASE) # 영문대소문자/숫자/공백/구두점 제외 제거
corpus = corpus.lower() # 소문자로 통일

en_stopwords = stopwords.words('english')

sentences = sent_tokenize(corpus) # 문장 리스트로 분리
normalized_sentences = []         # 문방별 정규화 토큰

for sent in sentences:
    tokens = word_tokenize(sent) # 토큰 리스트로 분리
    normalized_tokens = [token for token in tokens if token not in en_stopwords] # 불용어 제거
    normalized_sentences.append(normalized_tokens)

print(f"총 문장 수 : {len(normalized_sentences)}") 

총 문장 수 : 271088


In [33]:
%%time
from gensim.models.fasttext import FastText

model = FastText(
    normalized_sentences,
    vector_size=100,
    window=5,
    min_count=5,
    workers=4,
    sg=1
)

CPU times: total: 2min 7s
Wall time: 36.5 s


In [34]:
model.wv.vectors.shape

(22174, 100)

In [35]:
print(model.wv.most_similar('man'))

print(model.wv.similarity('man','woman'))

[('woman', 0.8413470983505249), ('batman', 0.786723256111145), ('hoffman', 0.7800272703170776), ('roman', 0.7501961588859558), ('shaman', 0.7481964230537415), ('manju', 0.7477266192436218), ('womans', 0.7423659563064575), ('lehman', 0.7410646080970764), ('wurman', 0.736449658870697), ('stuntman', 0.7292302846908569)]
0.8413472


In [36]:
print(model.wv.get_index('apple'))                # apple의 인덱스 확인
print(model.wv.vectors[1618][:5])                 # 1618번째 인덱스의 벡터 앞 5개
print(model.wv.get_vector('apple')[:5])           # apple 벡터 앞 5개

print(model.wv.get_index('applepie', -1))         # 사전에 없으면 -1
print(model.wv.get_vector('applepie')[:5])        # 사전에 없어도 벡터 생성
    

1618
[0.14042209 0.74514604 0.09987037 0.2332254  0.02178497]
[0.14042209 0.74514604 0.09987037 0.2332254  0.02178497]
-1
[ 0.05509283  0.39782634 -0.00255665  0.20015945  0.04668375]


In [37]:
# FastText 임베딩 구성 확인 : 단어 벡터 = (단어 자체 벡터 + 서브워드 벡터들) 평균
import numpy as np

word = 'apple'
word_vec = model.wv.get_vector(word)
print(word_vec[:5])

word_idx = model.wv.get_index(word)
print(word_idx)

base_vec = model.wv.vectors_vocab[word_idx]
print(base_vec[:5])

subword_index = model.wv.buckets_word[word_idx]
subword_vecs = model.wv.vectors_ngrams[subword_index]

print(subword_vecs.shape)
print(subword_vecs[:5])

calc_vec = np.vstack((base_vec, subword_vecs)).mean(axis=0)
print(calc_vec[:5])
print(word_vec[:5])


[0.14042209 0.74514604 0.09987037 0.2332254  0.02178497]
1618
[ 0.03930228  0.00664382  0.08681965 -0.00481187 -0.10430948]
(14, 100)
[[ 8.89401659e-02  1.74355721e+00  5.25623918e-01  6.80201828e-01
   4.93636042e-01 -4.94171560e-01 -7.21647382e-01  3.09011549e-01
  -1.03341214e-01 -1.37227035e+00  6.09169185e-01 -1.28917828e-01
  -6.44679189e-01  1.66096520e+00 -6.35811269e-01  5.85638821e-01
  -4.55818206e-01  3.30358326e-01 -2.30906874e-01 -3.60583961e-01
   2.34126732e-01  6.37247980e-01 -1.05312839e-01  2.86565781e-01
  -5.33562720e-01  8.18677008e-01  1.39258289e+00 -3.71087283e-01
   4.07542497e-01  2.91267708e-02  2.42887527e-01  9.00063157e-01
   1.07207274e+00  9.10004318e-01  7.08709052e-03  2.09045783e-01
   4.10216339e-02 -6.16755307e-01  7.05988348e-01 -7.92685747e-02
  -9.43734705e-01 -8.40641081e-01 -1.25582147e+00 -1.01376414e+00
  -1.40992141e+00 -1.06990874e+00 -7.15193808e-01 -2.69869417e-01
  -7.52739236e-02  5.13316333e-01  1.64159155e+00 -2.54869133e-01
   4.139

In [38]:
# 문장 벡터
sent_vec = model.wv.get_sentence_vector("I love apple very much~")
sent_vec.shape

(100,)

In [39]:
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

sentences = [" i love apple","apple is good","i hate banana","banana is yellow"]

# 각 문장을 학습된 모델로 문장 벡터로 변환 (2D 배열)
sent_vecs = np.array([model.wv.get_sentence_vector(sent) for sent in sentences])
print(sent_vecs.shape)

sent_cos_sim = cosine_similarity(sent_vecs)

pd.DataFrame(
    sent_cos_sim,
    columns = sentences,
    index = sentences
)

(4, 100)


,i love apple,apple is good,i hate banana,banana is yellow
i love apple,1.000000,0.927455,0.769365,0.900592
apple is good,0.927455,1.000000,0.694848,0.855151
i hate banana,0.769365,0.694848,1.000000,0.882806
banana is yellow,0.900592,0.855151,0.882806,1.000000


In [42]:
model.save('ted_en_fasttext.model') # 저장된 모델로 모델 객체 생성

In [43]:
model2 = FastText.load('ted_en_fasttext.model') # 저장된 모델로 모델 객체 생성
model2

In [44]:
model2.wv.most_similar("woman") #로드한 모델로 유사도 측정

[('womans', 0.8497938513755798),
 ('man', 0.8413472175598145),
 ('womanhood', 0.8245493173599243),
 ('hoffman', 0.7819695472717285),
 ('lehman', 0.7808048725128174),
 ('fireman', 0.7444190382957458),
 ('stroman', 0.7430051565170288),
 ('batman', 0.7412159442901611),
 ('womb', 0.7409908771514893),
 ('orphan', 0.7240606546401978)]