In [1]:
123

123

In [2]:
def numerical_diff(f, x, h=1e-4):
    return (f(x + h) - f(x - h)) / (2 * h)

def function(x):
    return x**2

print(numerical_diff(function, 3.0))

6.000000000012662


수치 미분은 조금 움직였을 때 값이 얼마나 변하는지 기울기를 추정할 때 사용한다.

딥러닝에서 실제 학습에서 사용하지는 않음

In [10]:
import torch

x = torch.FloatTensor([[1,2],
                       [3,4]]).requires_grad_(True)

In [11]:
x1 = x + 2
x2 = x - 2
x3 = x1 * x2
y = x3.sum()

print(x1)
print(x2)
print(x3)
print(y)

tensor([[3., 4.],
        [5., 6.]], grad_fn=<AddBackward0>)
tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>)
tensor([[-3.,  0.],
        [ 5., 12.]], grad_fn=<MulBackward0>)
tensor(14., grad_fn=<SumBackward0>)


In [12]:
y.backward() # y값을 기준으로 계산 그래프를 따라 연결된 모든 텐서의 기울기를 자동으로 계산

In [ ]:
print(x.grad) # y에 대해 계산된 x의 기울기(round y / round x)

tensor([[2., 4.],
        [6., 8.]])


y = ( x + 2) ( x - 2) 모두 합치면 y = (x^2-4)의 합

-4 미분 = 0
-> -4는 미분 결과에 영향 주지 않음

$
\frac{\partial}{\partial x_i}{x_i^2} = 2x_i
$

각 원소에 대해서
$\frac{\partial y}{\partial x_i} = 2x_i$

벡터 형태로 보면
${\partial y}{\partial x} = 2x$
결론적으로 x.grad 결과는 2x 형태로 나오게 된다.

In [ ]:
print(x) # 텐서값을 변경 없음, 역전파는 기울기를 계산만하고 수정하지않음 (기울기 추적 대상)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [17]:
x3.numpy() # numpy는 autograd 상태를 모르기 때문에 바로 numpy 형태로 변환은 되지않음

RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

In [19]:
x3.detach_().numpy()  # x3를 계산 그래프에서 분리(autograd 추적 제거)하고 numpy 배열로 반환

array([[-3.,  0.],
       [ 5., 12.]], dtype=float32)

detach() : 복사본을 만들면서 분리 (권장)                                                                                        
detach_() : 원본 자체를 분리(detach() + inplace 옵션)           

In [ ]:
x2 # 추적중 확인

tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>)

In [ ]:
x3 # numpy 배열 형태로 출력

tensor([[-3.,  0.],
        [ 5., 12.]])

In [22]:
def numerical_diff(f, x, h=1e-4):
    return (f(x + h) - f(x - h)) / (2 * h)

def function(x):
    return x**2

print(numerical_diff(function, 3.0))

6.000000000012662


손실을최소화하기위해서손실의반대방향으로가중치를수정한다.

$w \leftarrow w - \eta \frac{\partial L}{\partial w}$

w : 현재 가중치                   
<- 새 값으로 업데이트 (:=)
n (eta) 학습률
L : 손실함수                      
round L / round W : 가중치 w가 손실함수 L에 미치는 영향 (편미분, 기울기)
-는 손실을 줄이는 가장 효율적인 이동 방향