In [3]:
import numpy as np

def identity_function(x):
    return x

x = np.array([1.0, 2.0, 3.0])
print(identity_function(x))

[1. 2. 3.]


회귀문제도 신경망 내부에서 이미 은닉층을 거치면서 비선형 변환이 이루어진 상태이므로,                          
출력층에서는 그냥 나오는 출력값 그래도 사용한다.

In [4]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

x = np.array([0.0, 2.0, -1.0])
print(sigmoid(x))

[0.5        0.88079708 0.26894142]


Sigmoid 함수로 나온 예측확률을 임계값을 기준으로 예측 결과로서 결정             
출력값 >= 0.5 -> 클래스 1            
출력값 < 0.5 => 클래스 0        

- 활성화 함수로서 사용하지 않는 이유
출력이 0 또는 1에 가까워지면 기울기가 거의 0에 수렴되어 학습이 거의 되지 않아              
출력층에서만 사용한다             
손실함수로 BCE와 함께 사용        

In [5]:
def softmax(x):
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x)

x = np.array([2.0, 1.0, 0.1])
print(softmax(x))

[0.65900114 0.24243297 0.09856589]
