In [4]:
123

123

In [5]:
import torch

In [6]:
a = torch.FloatTensor([[1,2], 
                      [3,4]])
b = torch.FloatTensor([[1,2], 
                      [1,2]])   
c = torch.matmul(a,b)         # 행렬곱

c           


tensor([[ 3.,  6.],
        [ 7., 14.]])

In [7]:
d = a @ b
d

tensor([[ 3.,  6.],
        [ 7., 14.]])

In [8]:
a = torch.IntTensor([[1,2], 
                      [3,4]])
a

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

IntTensor도 선언 가능하지만 일반적으로 딥러닝에서 가중치, 출력값, 기울기 등 모든 연산이 실수 연산이므로,          
그래서 FloatTensor를 기본으로 사용한다.       

In [9]:
b = torch.LongTensor([[1,2], 
                      [3,4]])
b

tensor([[1, 2],
        [3, 4]])

In [10]:
c = torch.ByteTensor([[1,2], 
                      [3,4]])
c

tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)

In [11]:
mask = torch.BoolTensor([True, False, True])

mask

tensor([ True, False,  True])

In [12]:
x = torch.FloatTensor(3,2) # shape = (3,2)인 텐서

x

tensor([[-4.1202e+31,  1.4840e-42],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])

In [13]:
a = torch.zeros(3,2)  # (3,2) 0으로 채워진 텐서

a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [14]:
b = torch.ones(3,2)   # (3,2) 1로 채워진 텐서

b

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [15]:
c = torch.randn(3,2)  # 정규분포 난수

c

tensor([[-0.7579, -1.0817],
        [-0.1208,  0.1471],
        [ 0.5507,  0.3414]])

In [16]:
import numpy as np

x = np.array([[1,2],
              [3,4]])

print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [17]:
# Pytorch tensor로 변환
x = torch.from_numpy(x)

print(x, type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [18]:
# Pytorch Tensor를 Numpy ndarray형태로 변환
x = x.numpy()
print(x,type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [19]:
x = torch.from_numpy(x)

x.long()    #LongTensor(int64) 타입으로 변환. 소수점은 버림(분류 문제 정답라벨)

tensor([[1, 2],
        [3, 4]])

In [20]:
x.float()

print(x, type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [21]:
torch.FloatTensor([1,0]).bool()



tensor([ True, False])

In [22]:
x = torch.FloatTensor([[[1,2],
                        [3,4]],
                        [[5,6],
                        [7,8]],
                        [[9,10],
                        [11,12]]])

print(x.size())
print(x.shape)

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


In [23]:
print(x.dim())  # 텐서의 차원 수  (3,2,2) -> 3개의 차원

3


In [24]:
print(len(x.size()))   # 텐서의 길이 -> 차원 수

3


In [25]:
# 텐서의 특징 차원에 있는 요소의 개수
print(x.size(1))      # Pytorch 메서드 (1번 축 크기)
print(x.shape[1])     # Numpy 스타일 (1번 축 크기)

2
2


In [26]:
# 마지막 차원 요소 개수

print(x.size(-1))      # Pytorch 메서드 (마지막 축 크기)
print(x.shape[-1])     # Numpy 스타일 (마지막 축 크기)

2
2


# 텐서 연산

In [27]:
import torch

a = torch.FloatTensor([[1,2], 
                      [3,4]])
b = torch.FloatTensor([[1,2], 
                      [1,2]])   

a + b           

tensor([[2., 4.],
        [4., 6.]])

In [28]:
a - b

tensor([[0., 0.],
        [2., 2.]])

In [29]:
a * b

tensor([[1., 4.],
        [3., 8.]])

In [30]:
a / b

tensor([[1., 1.],
        [3., 2.]])

In [31]:
a == b

tensor([[ True,  True],
        [False, False]])

In [32]:
a != b

tensor([[False, False],
        [ True,  True]])

In [33]:
a ** b

tensor([[ 1.,  4.],
        [ 3., 16.]])

In [34]:
print(a.mul(b))

tensor([[1., 4.],
        [3., 8.]])


In [35]:
print(a.mul_(b))    # _가 붙은 연산은 원본 Tensor를 바꿔주는 in-place 역할

tensor([[1., 4.],
        [3., 8.]])


In [36]:
print(a)

tensor([[1., 4.],
        [3., 8.]])


In [37]:
print(a.sum())   # 전체의 합
print(a.mean())  # 전체의 평균

tensor(16.)
tensor(4.)


In [38]:
print(a.sum(dim = 0))   # 세로 방향으로 더하기 (행 축은 사라진다)
print(a.sum(dim = 1))   # 가로 방향으로 더하기 (열 축은 사라진다)

tensor([ 4., 12.])
tensor([ 5., 11.])


해당 dim 차원을 합치기 때문에 해당 축은 사라진다.

In [39]:
a.sum(dim = 0).shape

torch.Size([2])

In [40]:
a.sum(dim = 1).shape

torch.Size([2])

Broadcast : 텐서의 차원(크기)이 다를 때, 자동으로 차원을 확장해 차원을 맞춰주는 기능

In [41]:
x = torch.FloatTensor([[1,2]])
y = torch.FloatTensor([[4,8]])

print(x.shape, y.shape)

torch.Size([1, 2]) torch.Size([1, 2])


In [42]:
z = x + y
print(z, z.size())

tensor([[ 5., 10.]]) torch.Size([1, 2])


In [43]:
x = a = torch.FloatTensor([[1,2], 
                           [3,4]])
y = 1

print(x.shape)

torch.Size([2, 2])


In [44]:
z = x + y

print(z, z.shape)

tensor([[2., 3.],
        [4., 5.]]) torch.Size([2, 2])


```
1 ->  [[1,1],               
      [1,1]]
```

x와 동일한 shape로 브래드캐스팅(자동 형변환)


In [45]:
x = torch.FloatTensor([[1,2], 
                      [3,4]])
y = torch.FloatTensor([3,5])

print(x.shape, y.shape)

torch.Size([2, 2]) torch.Size([2])


In [46]:
z = x + y
print(z, z.size())

tensor([[4., 7.],
        [6., 9.]]) torch.Size([2, 2])


```
[3,5] -> [[3,5],
          [3,5]]
```
x의 행 수 만큼 복제가 된다

In [47]:
x = torch.FloatTensor([[[1,2]]])
y = torch.FloatTensor([3,5])

print(x.shape, y.shape)

torch.Size([1, 1, 2]) torch.Size([2])


마지막 차원수 2로 같기 때문에 나머지 차원은 y에 없으므로 자동으로 1로 확장

In [48]:
z = x + y
print(z, z.size())

tensor([[[4., 7.]]]) torch.Size([1, 1, 2])


In [49]:
x = torch.FloatTensor([[1,2]])
y = torch.FloatTensor([[3],
                        [5]])

print(x.shape, y.shape)

torch.Size([1, 2]) torch.Size([2, 1])


개수가 1인 차원은 확장된다.

In [50]:
z = x + y
print(z, z.size())

tensor([[4., 5.],
        [6., 7.]]) torch.Size([2, 2])


개수가 1인 차원은 확장된다.        
마지막 차원 2 와 1 -> 1이 확장되어 2
앞 차원 1 과 2 -> 1이 확장되어 2
=> (2,2)

```
[[1,2]] -> [[1,2],
           [1,2]]     # 행 방향으로 확장

[[3],   ->  [[3, 3],
 [5]]       [5, 5]]   # 열 방향으로 확장

In [51]:
# 잘못 사용된 예시
x = torch.FloatTensor([[[1,2],
                        [4,8]]])
y = torch.FloatTensor([[1,2,3],
                        [4,5,6],
                        [7,8,9]])

print(x.shape, y.shape)

torch.Size([1, 2, 2]) torch.Size([3, 3])


In [52]:
z = x + y  # 차원 에러 발생

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

0번 차원 : x는 1, y는 - => 자동 확장 가능
1번 차원 : x는 2, y는 3 => 다른데, 하나라도 1이면 가능하지만 둘다 1이 아님
2번 차원:  x는 2, y는 3 => 다른데, 하나라도 1이면 가능하지만 둘다 1이 아님

브로드캐스팅 조건: 각 ㅏ원의 값이 같거나, 하나가 1일 경우에만 자동 확장 가능

# 텐서 조작하기

In [53]:
x = torch.FloatTensor([[[1,2],
                        [3,4]],
                       [[5,6],
                         [7,8]],
                        [[9,10],
                        [11,12]]])

x.size()

torch.Size([3, 2, 2])

In [54]:
print(x.reshape(12))  # shape을 명시적으로 지정 (12개 요소를 가진 1차원 텐서)
print(x.reshape(-1))  # -1 : 자동 지정 (자동 지정되는 갯수의 요소를 가진 1차원 텐서)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [55]:
print(x.reshape(3,4))
print(x.reshape(3,-1))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [56]:
print(x.reshape(3,1,4))
print(x.reshape(-1,1,4))

tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


In [57]:
print(x.reshape(-1,-1,4)) # 자동 2개는 불가

RuntimeError: only one dimension can be inferred

In [58]:
print(x.reshape(3,2,2,1)) # 2행 2열 + 채널 1이 붙은 데이터 3개

tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.]]],


        [[[ 9.],
          [10.]],

         [[11.],
          [12.]]]])


view() : 연속된 메모리 구조일 때 사용한다.
reshape(): 필요시 데이터 복사도 가능한 유연한 재구성 함수

In [59]:
# squeeze() : 텐서에서 크기가 1인 차원 제거
x = torch.FloatTensor([[[1,2],
                        [3,4]]])

print(x.shape)

torch.Size([1, 2, 2])


In [60]:
print(x.squeeze(), x.squeeze().size())

tensor([[1., 2.],
        [3., 4.]]) torch.Size([2, 2])


In [61]:
# squeeze(차원) 특정 차원을 제거. 크기가 1일 경우에만

print(x.squeeze(0).size())
print(x.squeeze(1).size())

torch.Size([2, 2])
torch.Size([1, 2, 2])


In [62]:
# unsqueeze(): 특정 위치에 새 차원을 추가
x = torch.FloatTensor([[1,2],
                      [3,4]])

x.size()

torch.Size([2, 2])

In [63]:
print(x.unsqueeze(2), x.unsqueeze(2).size())  # 2번 차원
print(x.unsqueeze(-1), x.unsqueeze(-1).size()) # 마지막 차원
print(x.reshape(2,2,-1), x.reshape(2,2,-1).shape) # 동일

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]]) torch.Size([2, 2, 1])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]]) torch.Size([2, 2, 1])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]]) torch.Size([2, 2, 1])


차원 조작같은 경우 입력층 -> 은닉층 또는 은닉층 -> 출력층 부분에서
차원을 맞춰서 값을 넘겨야할 때 주로 사용한다.

텐서를 자르고 붙이기(인덱싱 & 슬라이싱)

In [64]:
x = torch.FloatTensor([[[1,2],
                        [3,4]],
                        [[5,6],
                        [7,8]],
                        [[9,10],
                        [11,12]]])

x.size()

torch.Size([3, 2, 2])

In [65]:
print(x[0]) # 첫 번째 차원(dim = 0)에서 인덱스 0 선택
print(x[0,:,:])  # 생략된 차원을 명시적으로 표시

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])


In [66]:
print(x[0, :])  # 첫 번째 차원 (dim = 0)에서 두 번째 차원 (dim = 1)을 (전체)선택

tensor([[1., 2.],
        [3., 4.]])


뒤쪽차원의 : 전체선택은 생략 가능하면 생략하면 자동으로 전체선택 처리된다

In [67]:
import torch

print(x[-1]) # 마지막 번째 차원(dim = 0)에서 인덱스 0 선택
print(x[-1,:]) # 마지막 차원 (dim=0)에서 두번째 차원(dim=1)을 : (전체) 선택
print(x[-1,:,:]) # 생략된 차원을 명시적으로 표시

tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])


In [68]:
print(x[:,0,:], x[:,0,:].size()) # 전체 배치에서 첫번째 행만 가져옴( 열 전체)

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]]) torch.Size([3, 2])


배치는 그대로 3 유지            
행은 선택되어 제거              
열은 그대로 2 유지              

In [69]:
# 슬라이싱으로 접근시 차원 수 유지
print(x[1:3, :, :], x[1:3, :, :].size())

tensor([[[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]]) torch.Size([2, 2, 2])


In [70]:
print(x[:,:1,:], x[:,:1,:].size()) # 모든 배치. 행은 앞의 1개만 슬라이싱, 열은 전체

tensor([[[ 1.,  2.]],

        [[ 5.,  6.]],

        [[ 9., 10.]]]) torch.Size([3, 1, 2])


In [71]:
print(x[:,:-1,:], x[:,:-1,:].size()) # 모든 배치. 행은 마지막 행 제외, 열은 전체

tensor([[[ 1.,  2.]],

        [[ 5.,  6.]],

        [[ 9., 10.]]]) torch.Size([3, 1, 2])


In [72]:
#split() : 텐서를 원하는 모양으로 나눠준다.

x = torch.FloatTensor(10,4)
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [73]:
splits = x.split(4,dim=0)

splits


(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.]]))

In [ ]:
# chunk() : 텐서를 청크 수로 나눈다.

x = torch.ones(8,4)

chunks = x.chunk(3, dim = 0) # 0번 차원 기준으로 3조각으로 나눔

for chunk in chunks:
    print(chunk.size())

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([2, 4])


 split(n,dim) : n개로 균등하게 분할         
chunk(size, dim) : size만큼 조각하여 자른다.      

In [75]:
# index_select() : 차원 인덱스를 사용하여 요소를 선택
x = torch.FloatTensor([[[1,2],
                        [3,4]],
                        [[5,6],
                        [7,8]],
                        [[9,10],
                        [11,12]]])

indice = torch.LongTensor([2,1])

x.size()

torch.Size([3, 2, 2])

In [ ]:
y = x.index_select(dim = 0, index = indice)  # 0번 차원 indice에서 지정한 순서대로 선택

print(y, y.size())

tensor([[[ 9., 10.],
         [11., 12.]],

        [[ 5.,  6.],
         [ 7.,  8.]]]) torch.Size([2, 2, 2])


index_select 함수는 반환값이 있어 텐서가 새로 생성되어 사용시 값으로 받아준다.        
index는 LongTensor형태로 전달해준다.        

In [77]:
x.index_select(0, index = torch.LongTensor([0,0]))

tensor([[[1., 2.],
         [3., 4.]],

        [[1., 2.],
         [3., 4.]]])

In [80]:
#cat(): 여러 텐서간에 연결

x = torch.FloatTensor([[1,2,3], 
                       [4,5,6],
                       [7,8,9]])
y = torch.FloatTensor([[10,11,12],
                       [13,14,15],
                       [16,17,18]]) 

print(x.size(), y.size())
                      

torch.Size([3, 3]) torch.Size([3, 3])


In [81]:
z = torch.cat([x,y], dim = 0)
print(z, z.size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]]) torch.Size([6, 3])


cat()으로 붙이는 축을 제외한 나머지 차원은 반드시 동일해야 이어 붙일 수 있다.    
2차원 Tensor 기준 dim = 0 : 행 증가    
2차원 Tensor 기준 dim = 1 : 열 증가      

In [83]:
z = torch.cat([x,y], dim = 1)                               #(3,6)
print(z, z.size())

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]]) torch.Size([3, 6])


In [ ]:
#stack() : 여러 텐서를 쌓아 새로운 차원을 만든다.
z = torch.stack([x,y]) # x, y 2차원 데이터를 2장 쌓아 (2,3,3) 형태로 만듬

print(z,z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]]) torch.Size([2, 3, 3])


cat(): 차원 수 동일. 기존 축에 그대로 이어 붙임        
stack(): 차원 수 +1. 새로운 축을 만들어 쌓음

In [ ]:
print(torch.stack([x,y]).size())
print(torch.cat([x,y]).size())

torch.Size([2, 3, 3])
torch.Size([6, 3])


In [ ]:
z = torch.stack([x,y], dim = -1) # feature, channel 차원 추가

print(z, z.size())

tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]]) torch.Size([3, 3, 2])


In [89]:
# cat()과 unsqueeze() 사용하여 stack 구현하기
z = torch.cat([x.unsqueeze(0), y.unsqueeze(0)], dim = 0)

print(z, z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]]) torch.Size([2, 3, 3])


In [91]:
# 반복문 결과를 하나로 병합해보기 (2,2) -> (5,2,2) 배치 데이터 생성시 사용
result = []
for i in range(5):
    x = torch.FloatTensor(2,2)
    result += [x]  # (2,2) 텐서를 리스트에 하나씩 추가

result = torch.stack(result) # 리스트 텐서들을 새로운 차원으로 쌓음
result.size()

torch.Size([5, 2, 2])

### pythorch 메서드

In [93]:
# expand(): 크기가 1인 차원을 지정된 크기만큼 확장. 같은 값이 반복된 것처럼 보이게 해준다.
x = torch.FloatTensor([[[1,2]],
                      [[3,4]]])

print(x.shape)

torch.Size([2, 1, 2])


In [94]:
y = x.expand(*[2,3,2]) # 기존 (2,1,2)에서 행 차원을 1-> 3 , 나머지 차원은 그대로 유치

print(y, y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]]) torch.Size([2, 3, 2])


expand()는 값을 복사하지는 않는다. 내부적으로 같은 메모리를 여러 번 참조해서 사용    
-메모리 효율성이 높다.

값 앞에 *는 unpacking은 list나 tuple형 데이터를 순차적으로 전달하기 위해 사용   

In [ ]:
y = x.expand(2,3,2)

In [95]:
# cat을 활용하여 expand 구현하기
y = torch.cat([x,x,x], dim = 1) # dim = 1(두번째 차원) 기준으로 x를 3번 이어붙임

print(y,y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]]) torch.Size([2, 3, 2])


In [96]:
# randperm(n) : 랜덤 순열. 0부터 n-1까지의 정수를 무작위로 섞은 순열 텐서를 반환

x = torch.randperm(10)

print(x, x.size())

tensor([3, 9, 7, 1, 0, 4, 5, 8, 6, 2]) torch.Size([10])


In [97]:
torch.randperm(3**3).reshape(3,3,-1) # 0~26 27개의 값. 3차원으로 재구성

print(x, x.size())

tensor([3, 9, 7, 1, 0, 4, 5, 8, 6, 2]) torch.Size([10])


In [99]:
#argmax() : 최대값 인덱스 반환

y = x.argmax(dim = -1, keepdim = True)  # 마지막 차원(열)에서 가장 큰 값의 인덱스를 반환하고 그 차원은 제거

print(y, y.size())

tensor([1]) torch.Size([1])


argmax(dim = k) : k번 차원에서 가장 큰 인덱스를 선택하고, 그 차원 제거

In [101]:
#topk() : 상위 k개의 값과 해당 인덱스를 튜플로 반환

values, indices = torch.topk(x, k = 1, dim = -1)

print(values, values.size())
print(indices, indices.size())

tensor([9]) torch.Size([1])
tensor([1]) torch.Size([1])


topk(k = 1)로 설정하면 argmax(keepdim = True)와 같은 결과

In [103]:
# topk를 이용해 정렬하기
target_dim = -1
values, indices = torch.topk(
    x,
    k = x.size(target_dim),
    largest = True
)

print(values, values.size())

tensor([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]) torch.Size([10])


 x [ i, j, :]을 큰 값 기준으로 내림차순 정렬
- 차원 수는 그대로 유지. 값의 순서만 바뀜
- 각 줄에서는 큰 값 -> 작은 값 순서로 정렬
- indices는 정렬되기 전 위치값
- 결과적으로 topk(k = 차원크기)를 주면 해당 차원을 기준으로 정렬한 효과를 얻는다.

In [104]:
k = 1
values, indices = torch.sort(x, dim = -1, descending = True) # 마지막 차원을 기준으로 내림차순 정렬 (값, 원래위치)
values, indices = values[:,:,:k], indices[:,:,:k]            # 정렬된 결과 중 가장 큰 값 1개 선택(3,3,1)

print(values.squeeze(-1), values.squeeze(-1).size())         # (3,3,1) -> (3,3)
print(indices.squeeze(-1), indices.squeeze(-1).size())       # (3,3,1) -> (3,3)



IndexError: too many indices for tensor of dimension 1

sort + 슬라이싱 = topk 사용과 동일한 효과를 얻는다.

In [105]:
# masked_fill() : 마스크가 True인 위치에 지정한 값을 채움
x = torch.FloatTensor([i for i in range(3**2)]).reshape(3,-1)

print(x, x.size())

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]) torch.Size([3, 3])


In [106]:
torch.FloatTensor([i for i in range(3**2)]).reshape(1,1,-1).size() # 1, 1, 9 (-1)은 자동계산

torch.Size([1, 1, 9])

In [107]:
mask = x > 4

mask

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])

In [109]:
y = x.masked_fill(mask, value = -1) # mask가 True인 위치를 -1로 채움

print(y,y.size())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]]) torch.Size([3, 3])


사용처
- 이미치 처리 padding 처리
- loss 계산에서 해당 값 무시

In [110]:
# ones(), zeros() : 모든 요소가 0 또는 1로 채워진 텐서 반환
print(torch.ones(2,3))
print(torch.zeros(2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [113]:
print(x.size(), y.size())

torch.Size([3, 3]) torch.Size([3, 3])


In [114]:
# ones_like(), zeros_like() : 기준 텐서와 동일한 형태의 초기화 텐서 반환
print(torch.ones_like(x))
print(torch.zeros_like(y))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
import numpy as np

def perceptron(x1, x2, weights, bias):
    x = np.array([x1, x2])               # 입력값을 하나의 vector로 묶음
    w = np.array(weights)                # 가중치 리스트를 벡터로 변환
    return int(np.dot(x, w) + bias > 0)
    # return 1 if (w1*x1 + w2*x2 + b) > 0 else 0

# AND Gate
print("AND:", perceptron(1, 1, [0.5, 0.5], -0.7))

# NAND Gate (AND 연산을 반대로)
print("NAND:", perceptron(1, 1, [-0.5, -0.5], 0.7))

# OR Gate
print("OR:", perceptron(1, 0, [0.5, 0.5], -0.2))

AND: 1
NAND: 0
OR: 1


AND NAND OR 연산은 단층 퍼셉트론에서 해결 가능


In [116]:
def weighted_sum(inputs, weights, bias):
    return np.dot(inputs, weights) + bias

inputs = [1, 0]
weights = [0.8, -0.5]
bias = 0.2
output = weighted_sum(inputs, weights, bias)
print("Weighted Sum:", output)

Weighted Sum: 1.0


In [121]:
from sklearn.neural_network import MLPClassifier

# XOR 문제 해결
X = [[0, 0], [0, 1], [1, 0], [1, 1]]
y = [0, 1, 1, 0]

mlp = MLPClassifier(hidden_layer_sizes=(5,10),   # 은닉층 1개층, 뉴런 2개
                    activation='relu',         # relu 활성화함수(가장 보편적으로 사용하는 활성화함수)
                    max_iter=1000)             # epochs
mlp.fit(X, y)

print("Prediction:", mlp.predict(X))

Prediction: [0 1 1 0]


c:\Users\SJ\DL\dl_venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


activation : 은닉층에서 사용할 활성화 함수
- 입력에 비선형성을 추가해 복잡한 패턴 인식하는 함수

    - relu : 가장 일반적으로 사용, 학습 빠름
    - Leakt Relu : 음수 영역에 작은 기울기 허용 (죽은 ReLU 문제 완화)
    - ELU, GELU : Transformer 계열에서 사용

-tanh : 출력 범위가 -1 ~ 1로 나오는게 의미있을 때 사용
    - 입력/출력이 0을 중심으로 대칭
    - RNN계열 (LSTM, GRU)   

- logistic : 시그모이드 함수 (초기 신경망)



-출력층에서 사용할 활성화 함수와 구별을 잘 해야 한다.
이진 분류 : sigmoid (출력범위 0~1) -> 확률로 해석
다중 분류 : softmax (출력범위 0~1. 총합이 1) -> 각 클래스에 대한 확률 분포
회귀: linear(없음) -> 예측값 그대로 사용